"""Shared fixtures for reindex unit tests.

The fixture corpus under tests/fixtures/corpus/ is VERBATIM copies of live
guardkit corpus files (anti-fiction law: every classifier/parser fixture is a
copy of a real file, never authored from the spec). Each carries an attribution
comment naming its source path.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from fleet_memory.reindex.manifest import CorpusManifest, load_manifest
from fleet_memory.reindex.walker import CorpusDocument

FIXTURES_DIR = Path(__file__).resolve().parents[2] / "fixtures"
CORPUS_ROOT = FIXTURES_DIR / "corpus"
MANIFEST_PATH = FIXTURES_DIR / "corpus_manifest.json"


@pytest.fixture
def corpus_root() -> Path:
    """Root of the verbatim fixture corpus."""
    return CORPUS_ROOT


@pytest.fixture
def manifest() -> CorpusManifest:
    """The guardkit corpus manifest (generated by the real exporter)."""
    return load_manifest(MANIFEST_PATH)


@pytest.fixture
def load_doc(corpus_root: Path):
    """Load a fixture corpus file as a CorpusDocument by repo-relative path."""

    def _load(relative_path: str) -> CorpusDocument:
        path = (corpus_root / relative_path).resolve()
        return CorpusDocument(path=path, text=path.read_text(encoding="utf-8"))

    return _load
